# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common/terms.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


#from google.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2  # works
from google_test.protobuf import descriptor_pb2 as google_dot_protobuf_dot_descriptor__pb2  # broken
from common import options_pb2 as common_dot_options__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12\x63ommon/terms.proto\x12\x06\x63ommon\x1a google/protobuf/descriptor.proto\x1a\x14\x63ommon/options.proto*)\n\nTermSource\x12\x1b\n\x17TERM_SOURCE_UNSPECIFIED\x10\x00\x42\x04\x90\xf1\x19\x01\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.terms_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\220\361\031\001'
  _TERMSOURCE._serialized_start=86
  _TERMSOURCE._serialized_end=127
# @@protoc_insertion_point(module_scope)
